name: Change shell
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - shell: bash # シェルにBashを指定
              run: echo "${shell}"
            - shell: python # シェルにPythonを指定
              run: |
                import os
                print(os.environ['PATH'])
