name: Compare functions
on: push
jobs:
    compare:
        runs-on: ubuntu-latest
        steps:
            - run: printenv | grep '_FUNC'
              env:
                CONTAINS_FUNC: ${{ contains('Hello', 'ell') }} # 第一引数の文字列'Hello'が、第二引数の文字列'ell'を含むか
                STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }} # 第一引数の文字列'Hello'が、第二引数の文字列'He'で始まるか
                ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }} # 第一引数の文字列'Hello'が、第二引数の文字列'lo'で終わるか