name: Naming # ワークフロー名
on: push # トリガー
jobs:
    print: # ジョブID
        name: Super Useful Job # ジョブ名の指定
        runs-on: ubuntu-latest
        steps:
            - name: Amazing Script # ステップ名の指定
              run: echo "Hello"